name: metaweather_api
description: A metaweather package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1

dev_dependencies:
  pedantic: ^1.11.0

flutter:
