name: blizzard
description: A weather app.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  weather_repository:
    path: packages/weather_repository
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  bloc_test: 8.0.0
  mockito: 5.0.5

flutter:
  uses-material-design: true
