name: weather_repository
description: A weather respository.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  metaweather_api:
      path: ../metaweather_api
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.11.0
