name: weather_repository
description: A weather respository.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  metaweather_api:
      path: ../metaweather_api

dev_dependencies:
  pedantic: ^1.11.0
